# Generated by Django 5.2.1 on 2025-05-28 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('iso_code', models.CharField(max_length=3, unique=True)),
                ('region', models.CharField(max_length=100)),
                ('income_level', models.CharField(choices=[('low', 'Low Income'), ('lower_middle', 'Lower Middle Income'), ('upper_middle', 'Upper Middle Income'), ('high', 'High Income')], max_length=50)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('gdp_per_capita', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('donor_type', models.CharField(choices=[('bilateral', 'Bilateral'), ('multilateral', 'Multilateral'), ('private', 'Private Foundation'), ('ngo', 'NGO'), ('other', 'Other')], max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImplementingOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('org_type', models.CharField(choices=[('government', 'Government Agency'), ('ngo', 'NGO'), ('private', 'Private Sector'), ('international', 'International Organization'), ('academic', 'Academic Institution'), ('other', 'Other')], max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.country')),
            ],
        ),
        migrations.CreateModel(
            name='AidProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iati_identifier', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('activity_status', models.CharField(choices=[('pipeline', 'Pipeline/Identification'), ('implementation', 'Implementation'), ('completion', 'Completion'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], max_length=50)),
                ('start_date_planned', models.DateField()),
                ('end_date_planned', models.DateField()),
                ('start_date_actual', models.DateField(blank=True, null=True)),
                ('end_date_actual', models.DateField(blank=True, null=True)),
                ('sub_national_location', models.CharField(blank=True, max_length=200, null=True)),
                ('collaboration_type', models.CharField(blank=True, choices=[('bilateral', 'Bilateral'), ('multilateral', 'Multilateral'), ('triangular', 'Triangular Cooperation')], max_length=50, null=True)),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('funding_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('default_flow_type', models.CharField(blank=True, choices=[('oda', 'Official Development Assistance'), ('oof', 'Other Official Flows'), ('private', 'Private Flows'), ('other', 'Other')], max_length=50, null=True)),
                ('default_finance_type', models.CharField(blank=True, choices=[('grant', 'Grant'), ('loan', 'Standard Loan'), ('concessional_loan', 'Concessional Loan'), ('equity', 'Equity Investment'), ('guarantee', 'Guarantee/Insurance'), ('other', 'Other')], max_length=50, null=True)),
                ('default_aid_type', models.CharField(blank=True, choices=[('budget_support', 'Budget Support'), ('project_intervention', 'Project-type Intervention'), ('technical_assistance', 'Technical Assistance'), ('scholarship', 'Scholarship/Training'), ('debt_relief', 'Debt Relief'), ('other', 'Other')], max_length=50, null=True)),
                ('default_tied_status', models.CharField(blank=True, choices=[('untied', 'Untied'), ('tied', 'Tied'), ('partially_tied', 'Partially Tied')], max_length=50, null=True)),
                ('contact_info', models.TextField(blank=True, null=True)),
                ('document_link', models.URLField(blank=True, null=True)),
                ('partner_activity_id', models.CharField(blank=True, max_length=255, null=True)),
                ('target_beneficiaries', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_beneficiaries', models.PositiveIntegerField(blank=True, null=True)),
                ('results_description', models.TextField(blank=True, null=True)),
                ('impact_assessment', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('recipient_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.country')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.donor')),
                ('implementing_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.implementingorganization')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.sector')),
            ],
            options={
                'verbose_name': 'Aid Project',
                'verbose_name_plural': 'Aid Projects',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='projects.aidproject')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('proposal', 'Project Proposal'), ('agreement', 'Agreement'), ('report', 'Progress Report'), ('evaluation', 'Evaluation'), ('financial', 'Financial Report'), ('other', 'Other')], max_length=50)),
                ('file_url', models.URLField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.aidproject')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('planned_date', models.DateField()),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.aidproject')),
            ],
            options={
                'ordering': ['planned_date'],
            },
        ),
    ]
