# Generated by Django 5.2.1 on 2025-05-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_userprofile_secondary_email_alter_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='iati_identifier',
            field=models.CharField(blank=True, help_text='IATI organization identifier', max_length=200, null=True, unique=True),
        ),
    ]
