# Generated by Django 5.2.1 on 2025-05-30 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_add_location_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commitment_type', models.CharField(choices=[('total_commitment', 'Total Commitment'), ('annual_commitment', 'Annual Commitment'), ('conditional_commitment', 'Conditional Commitment')], default='total_commitment', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('MMK', 'Myanmar Kyat'), ('JPY', 'Japanese Yen'), ('CNY', 'Chinese Yuan'), ('THB', 'Thai Baht')], default='USD', max_length=3)),
                ('commitment_date', models.DateField()),
                ('description', models.TextField(blank=True, help_text='Commitment description or notes')),
                ('reference', models.CharField(blank=True, help_text='Commitment reference number', max_length=100)),
                ('iati_identifier', models.CharField(blank=True, max_length=200)),
                ('aid_type', models.CharField(blank=True, max_length=50)),
                ('flow_type', models.CharField(blank=True, max_length=50)),
                ('tied_status', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='projects.aidproject')),
                ('provider_organization', models.ForeignKey(blank=True, help_text='Organization providing the commitment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provided_commitments', to='projects.organization')),
                ('receiver_organization', models.ForeignKey(blank=True, help_text='Organization receiving the commitment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_commitments', to='projects.organization')),
            ],
            options={
                'ordering': ['-commitment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('disbursement', 'Disbursement'), ('expenditure', 'Expenditure'), ('incoming_funds', 'Incoming Funds'), ('loan_repayment', 'Loan Repayment'), ('interest_payment', 'Interest Payment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('MMK', 'Myanmar Kyat'), ('JPY', 'Japanese Yen'), ('CNY', 'Chinese Yuan'), ('THB', 'Thai Baht')], default='USD', max_length=3)),
                ('transaction_date', models.DateField()),
                ('description', models.TextField(blank=True, help_text='Transaction description or notes')),
                ('reference', models.CharField(blank=True, help_text='Transaction reference number', max_length=100)),
                ('iati_identifier', models.CharField(blank=True, max_length=200)),
                ('aid_type', models.CharField(blank=True, max_length=50)),
                ('flow_type', models.CharField(blank=True, max_length=50)),
                ('tied_status', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='projects.aidproject')),
                ('provider_organization', models.ForeignKey(blank=True, help_text='Organization providing the funds', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provided_transactions', to='projects.organization')),
                ('receiver_organization', models.ForeignKey(blank=True, help_text='Organization receiving the funds', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to='projects.organization')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
