# Generated by Django 5.2.1 on 2025-07-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_add_import_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidproject',
            name='default_modality',
            field=models.IntegerField(blank=True, choices=[(1, 'Grant – Non-repayable funds, typically public sector support'), (2, 'Loan – Repayable funds with terms and conditions'), (3, 'Technical Assistance – Personnel, training, or capacity support'), (4, 'Reimbursable Grant or Other – Partial repayment or hybrid arrangement'), (5, 'Investment/Guarantee – Risk capital or financial instruments without cash transfer')], null=True),
        ),
        migrations.AddField(
            model_name='aidproject',
            name='default_modality_override',
            field=models.BooleanField(default=False),
        ),
    ]
