-- ============================================================================
-- ENRICHMENT: Myanmar Activity Detail Patch
-- Adds richer descriptions, collaboration types, custom dates, and
-- other identifiers to the activities seeded by seed_myanmar_activities.sql
-- ============================================================================

-- ============================================================================
-- ACTIVITY 1: Rural Primary School Construction and Teacher Training Program
-- XM-DAC-701-MM-EDU-2023-001
-- ============================================================================
UPDATE activities SET
    iati_identifier = 'XM-DAC-701-MM-EDU-2023-001',
    description_narrative = 'The Rural Primary School Construction and Teacher Training Program (RPSCTP) is a five-year initiative implemented by JICA in partnership with Myanmar''s Ministry of Education. Operating across Shan, Kayah, and Kayin States — three of Myanmar''s most geographically isolated and educationally underserved regions — the program addresses the twin barriers of inadequate infrastructure and undertrained teaching staff. Baseline surveys conducted in 2022 identified 78 communities where the nearest functioning school was more than 5 kilometres from the population centre, forcing families to choose between education and safety for children. This program constructs 50 new earthquake-resistant school buildings to JICA''s resilient design standard, each equipped with gender-segregated WASH facilities, rainwater harvesting systems, and solar lighting. In parallel, a structured in-service teacher development curriculum delivered across 12 residential training hubs trains 500 primary educators in child-centred learning, mother-tongue-based multilingual education, and psychosocial support techniques appropriate to conflict-affected contexts. Community governance is embedded through the establishment of 50 Parent-Teacher Associations with formal school improvement mandates and small discretionary grants.',
    description_objectives = 'Outcome 1 — Access: Construct 50 earthquake-resistant primary school buildings with WASH facilities in communities currently lacking a school within 5 km, increasing enrolment by a minimum of 8,000 children by project year 3. Outcome 2 — Quality: Train 500 in-service primary teachers using a nationally accredited 120-hour professional development curriculum, achieving a measured improvement in classroom observation scores of at least 25% from baseline. Outcome 3 — Governance: Establish 50 functioning Parent-Teacher Associations, each with a three-year school improvement plan and a community maintenance fund, reducing school dropout rates attributable to facility disrepair by 40% within the project period. Outcome 4 — Equity: Ensure that a minimum of 48% of enrolled students are girls and that children with disabilities are accommodated through inclusive design features in all newly constructed facilities.',
    description_target_groups = 'Primary beneficiaries are approximately 40,000 children aged 5 to 11 living in rural communities across Shan, Kayah, and Kayin States, with particular attention to girls, children from ethnic minority backgrounds (including Shan, Kayah, and Karen communities), and children with physical disabilities. Secondary beneficiaries include 500 primary school teachers — with a target of at least 40% women — who will receive accredited professional development. Tertiary beneficiaries are parents and community members, particularly mothers and women community leaders, who will be involved in school governance through Parent-Teacher Associations and community construction oversight committees.',
    collaboration_type = '1',  -- Bilateral
    other_identifiers = '[
        {"type": "A1", "reference": "JICA-MM-EDU-RP-2023-001", "owner_org_ref": "XM-DAC-701", "owner_org_name": "Japan International Cooperation Agency"},
        {"type": "A2", "reference": "CRS-2023-701-11220-001", "owner_org_ref": "XM-DAC-701", "owner_org_name": "Japan International Cooperation Agency"},
        {"type": "A9", "reference": "MOE-MM-2023-EDU-SCH-001", "owner_org_ref": "MM-GOV-MOE", "owner_org_name": "Ministry of Education"}
    ]'::jsonb,
    custom_dates = '[
        {"label": "Government MOU Signing", "date": "2023-03-15", "description": "Date on which JICA and the Ministry of Education signed the Memorandum of Understanding governing the program."},
        {"label": "First School Handover", "date": "2024-08-20", "description": "Date of the first completed school building handed over to the local community in Shan State."},
        {"label": "Mid-Term Review", "date": "2025-04-30", "description": "Scheduled independent mid-term evaluation to assess progress against outcome indicators and adjust implementation if required."}
    ]'::jsonb
WHERE id = 'a1000001-0001-4000-8000-000000000001'::UUID;

-- ============================================================================
-- ACTIVITY 2: Maternal and Child Health Programme
-- XM-DAC-41122-MM-MCH-2022-002
-- ============================================================================
UPDATE activities SET
    iati_identifier = 'XM-DAC-41122-MM-MCH-2022-002',
    description_narrative = 'The Maternal and Child Health Programme is a UNICEF-led initiative operating in partnership with Myanmar''s Ministry of Health and Sports across six townships in Sagaing, Magway, and Rakhine Regions. The programme responds to persistently high maternal mortality rates — estimated at 282 per 100,000 live births at baseline — and acute malnutrition affecting approximately 29% of children under five in target areas. Delivery is structured around three mutually reinforcing pillars: strengthening facility-based obstetric and neonatal care; scaling community health worker networks to extend preventive and promotive services to households; and improving the nutritional status of women and young children through therapeutic feeding, micronutrient supplementation, and behaviour change communication. The programme works within existing Ministry of Health systems and invests in supply chain reliability, cold chain maintenance, and health information systems to produce durable improvements beyond the project period. A robust community feedback mechanism, including grievance redress procedures, is embedded in programme design to ensure accountability to affected populations.',
    description_objectives = 'Objective 1: Reduce maternal mortality in target townships by 30% from the 2022 baseline of 282 per 100,000 live births through improved access to skilled birth attendance and emergency obstetric care. Objective 2: Reduce the prevalence of acute malnutrition (wasting) among children under five from 29% to below 15% in target areas through integrated nutrition interventions including therapeutic feeding, vitamin A supplementation, and iron-folic acid distribution. Objective 3: Increase the proportion of pregnant women attending at least four antenatal care visits from 54% to 80% in target townships within 36 months. Objective 4: Train and deploy 240 community health workers with a minimum competency certification in antenatal and postnatal care, family planning counselling, and community-based management of acute malnutrition.',
    description_target_groups = 'Direct beneficiaries include approximately 85,000 women of reproductive age (15–49) residing in the six target townships, with a focus on pregnant and lactating women. An estimated 32,000 children under five, particularly those under two years of age (the critical window for nutrition interventions), are targeted for nutrition screening, therapeutic feeding, and immunisation catch-up. Community health workers — prioritising women from the communities they serve — are a key secondary beneficiary group who receive skills-based training, supervision, and performance-based incentives. Health facility staff including midwives, nurses, and medical officers benefit from clinical skills upgrading and access to essential medicines and equipment.',
    collaboration_type = '2',  -- Multilateral (inflows)
    other_identifiers = '[
        {"type": "A1", "reference": "UNICEF-MM-MCH-2022-SAG-MAG-RAK", "owner_org_ref": "XM-DAC-41122", "owner_org_name": "United Nations Children''s Fund"},
        {"type": "A3", "reference": "UNICEF-MM-HEALTH-2019-001", "owner_org_ref": "XM-DAC-41122", "owner_org_name": "United Nations Children''s Fund"},
        {"type": "A9", "reference": "MOHS-MM-MCH-2022-002", "owner_org_ref": "MM-GOV-MOHS", "owner_org_name": "Ministry of Health and Sports"}
    ]'::jsonb,
    custom_dates = '[
        {"label": "Programme Inception Workshop", "date": "2022-09-05", "description": "Multi-stakeholder inception workshop convened to validate the programme''s theory of change, confirm township selection, and agree baseline data collection methodology."},
        {"label": "Community Health Worker Certification Round 1", "date": "2023-05-12", "description": "First cohort of 120 community health workers certified following completion of the 45-day pre-service training curriculum."},
        {"label": "Nutrition Survey — Midline", "date": "2024-07-01", "description": "Scheduled population-based midline nutrition survey to measure changes in wasting prevalence and coverage of nutrition interventions against baseline."}
    ]'::jsonb
WHERE id = 'a1000001-0001-4000-8000-000000000002'::UUID;

-- ============================================================================
-- ACTIVITY 3: Smallholder Agricultural Development Programme
-- XM-DAC-46004-MM-AGR-2021-003
-- ============================================================================
UPDATE activities SET
    iati_identifier = 'XM-DAC-46004-MM-AGR-2021-003',
    description_narrative = 'The Smallholder Agricultural Development Programme is a six-year initiative co-financed by the Asian Development Bank and Myanmar''s Ministry of Agriculture, Livestock and Irrigation. The programme operates across the dry zone districts of Magway and Mandalay Regions — an area chronically vulnerable to drought and soil degradation — and targets the structural constraints limiting smallholder productivity: fragmented landholdings, limited access to certified seeds and quality inputs, underdeveloped irrigation infrastructure, and weak market linkages. The programme combines physical infrastructure investment (small-scale irrigation rehabilitation covering 25,000 hectares), agricultural technology transfer (climate-smart varieties, integrated pest management, post-harvest handling), cooperative and value chain development (formation and capacity building of 180 farmer cooperatives), and a rural finance component linking cooperatives to participating financial institutions for seasonal and investment credit. A gender-transformative approach is embedded throughout, with women''s leadership in cooperatives and women''s access to land tenure supported by dedicated capacity building and community dialogue. Environmental safeguards address water use efficiency, pesticide management, and soil health monitoring.',
    description_objectives = 'Objective 1 — Productivity: Increase average cereal yields among participating smallholder households by 35% within four years through the adoption of improved seed varieties, balanced fertiliser application, and integrated pest management. Objective 2 — Water Security: Rehabilitate and improve small-scale irrigation infrastructure serving 25,000 hectares, increasing cropping intensity from 1.2 to 1.8 crops per year in targeted schemes. Objective 3 — Market Access: Establish and capacitate 180 farmer cooperatives with legal registration, governance training, and access to collective marketing arrangements, increasing the average farm-gate price received by members by 20%. Objective 4 — Finance: Facilitate access to seasonal credit for at least 15,000 smallholder households through linkages with participating rural financial institutions, reducing dependence on exploitative informal lending. Objective 5 — Gender: Ensure women constitute at least 40% of cooperative leadership positions and that women-headed households receive targeted support for land tenure documentation.',
    description_target_groups = 'The primary beneficiary group comprises 50,000 smallholder farming households in Magway and Mandalay dry zone districts, of which an estimated 35% are women-headed. Within this group, particular priority is given to households farming less than 2 acres, households without formal land title, and households with members who have returned from urban migration. Secondary beneficiaries include members of 180 farmer cooperatives (approximately 12,000 individuals), rural financial institution staff who receive agricultural lending methodology training, and agricultural extension officers from the Department of Agriculture who are co-deployed as programme facilitators. Local agro-dealers and input suppliers benefit indirectly through increased demand for certified seeds and fertilisers.',
    collaboration_type = '4',  -- Multilateral outflows
    other_identifiers = '[
        {"type": "A1", "reference": "ADB-MM-AGR-2021-46004-003", "owner_org_ref": "XM-DAC-46004", "owner_org_name": "Asian Development Bank"},
        {"type": "A2", "reference": "CRS-2021-46004-31161-003", "owner_org_ref": "XM-DAC-46004", "owner_org_name": "Asian Development Bank"},
        {"type": "A9", "reference": "MOALI-MM-DRY-ZONE-2021-003", "owner_org_ref": "MM-GOV-MOALI", "owner_org_name": "Ministry of Agriculture, Livestock and Irrigation"}
    ]'::jsonb,
    custom_dates = '[
        {"label": "Feasibility Study Completion", "date": "2021-02-28", "description": "Date on which the ADB-commissioned feasibility study and environmental and social impact assessment were finalised and accepted by the Government."},
        {"label": "Irrigation Rehabilitation Phase 1 Completion", "date": "2023-11-30", "description": "Target completion date for civil works on the first 8,000 hectares of irrigation scheme rehabilitation in Magway Region."},
        {"label": "Cooperative Formation Target Date", "date": "2024-06-30", "description": "Milestone by which 120 of the 180 target farmer cooperatives are to be legally registered and have completed initial governance training."}
    ]'::jsonb
WHERE id = 'a1000001-0001-4000-8000-000000000003'::UUID;

-- ============================================================================
-- ACTIVITY 4: Rural WASH Infrastructure Programme
-- XM-DAC-801-MM-WASH-2022-004
-- ============================================================================
UPDATE activities SET
    iati_identifier = 'XM-DAC-801-MM-WASH-2022-004',
    description_narrative = 'The Rural WASH Infrastructure Programme is a four-year initiative funded by Australia''s Department of Foreign Affairs and Trade and implemented through Myanmar''s Ministry of Planning, Finance and Industry in partnership with local civil society organisations. The programme addresses the absence of safe drinking water and basic sanitation facilities in 200 remote villages across Chin and Kayah States and Sagaing Region — areas where open defecation rates exceed 60% and diarrhoeal disease is among the leading causes of under-five mortality. The programme follows a community-led total sanitation approach, combining capital investment in gravity-fed and solar-powered water supply systems (piped schemes serving clusters of villages as well as individual household connections where feasible), household latrine construction with targeted subsidies for the poorest households, and handwashing station installation at schools and health facilities. Community Water and Sanitation Committees are formed and trained in technical operation, financial management, and water quality testing to ensure post-construction sustainability. The programme integrates menstrual hygiene management into its school sanitation component and applies a disability-inclusive design standard to all public facilities.',
    description_objectives = 'Objective 1: Provide at least 80,000 rural residents in 200 target villages with access to a basic safe drinking water source within 30 minutes round trip, meeting WHO/UNICEF Joint Monitoring Programme definitions. Objective 2: Eliminate open defecation in all 200 target villages by programme end, verified through independent Open Defecation Free (ODF) certification, by constructing or subsidising approximately 16,000 household latrines and installing 400 community latrine blocks. Objective 3: Establish and operationalise 200 Community Water and Sanitation Committees, each with a trained water quality monitor, a maintained spare parts fund, and a documented tariff collection system sufficient to cover operation and maintenance costs. Objective 4: Install WASH facilities (separate toilets for girls and boys, handwashing stations, and menstrual hygiene management spaces) in 80 schools and 40 health facilities in target areas.',
    description_target_groups = 'Direct beneficiaries are approximately 80,000 rural residents across 200 villages, with particular focus on women and girls (who bear disproportionate burdens from inadequate WASH), children under five (most vulnerable to waterborne disease), persons with disabilities (who face access barriers to standard latrine designs), and school-age girls (for whom inadequate menstrual hygiene management facilities contribute to school dropout). Community Water and Sanitation Committee members — with a target of at least 50% women — are a key secondary beneficiary who receive sustained technical and management training. Teachers and health workers at programme-supported facilities benefit from improved working conditions and training in WASH-in-schools and WASH-in-health-facility protocols.',
    collaboration_type = '1',  -- Bilateral
    other_identifiers = '[
        {"type": "A1", "reference": "DFAT-MM-WASH-2022-CHIN-KAYAH-SAG", "owner_org_ref": "XM-DAC-801", "owner_org_name": "Department of Foreign Affairs and Trade"},
        {"type": "A2", "reference": "CRS-2022-801-14031-004", "owner_org_ref": "XM-DAC-801", "owner_org_name": "Department of Foreign Affairs and Trade"},
        {"type": "B1", "reference": "AusAID-MM-WASH-2019-004", "owner_org_ref": "XM-DAC-801", "owner_org_name": "AusAID (previous reporting organisation identifier)"}
    ]'::jsonb,
    custom_dates = '[
        {"label": "Village Selection Completed", "date": "2022-11-15", "description": "Date on which the participatory vulnerability and capacity assessment across candidate villages was finalised and the 200 target villages officially confirmed."},
        {"label": "First ODF Village Certification", "date": "2024-03-22", "description": "Date on which the first village in Chin State received independent Open Defecation Free certification following community-led total sanitation triggering and construction."},
        {"label": "End-Line Survey", "date": "2026-05-31", "description": "Scheduled independent end-line household survey and Water Point Mapping exercise to measure access, use, and functionality rates against baseline indicators."}
    ]'::jsonb
WHERE id = 'a1000001-0001-4000-8000-000000000004'::UUID;
