# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_converter', '0001_add_usd_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3, help_text='ISO 4217 currency code')),
                ('date', models.DateField(help_text='Date for the exchange rate')),
                ('rate_to_usd', models.DecimalField(max_digits=20, decimal_places=6, help_text='Exchange rate to USD')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('currency', 'date')},
                'indexes': [
                    models.Index(fields=['currency', 'date'], name='currency_date_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='SupportedCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, help_text='ISO 4217 currency code')),
                ('name', models.CharField(max_length=100, help_text='Currency name')),
                ('is_supported', models.BooleanField(default=True, help_text='Whether this currency is supported by our API')),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]