# Generated by Django 5.2.1 on 2025-05-29 14:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_aidproject_prism_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('operational', 'Operational'), ('management', 'Management'), ('technical', 'Technical'), ('administrative', 'Administrative')], default='operational', max_length=20)),
                ('can_create_projects', models.BooleanField(default=True)),
                ('can_edit_own_projects', models.BooleanField(default=True)),
                ('can_edit_org_projects', models.BooleanField(default=False)),
                ('can_approve_projects', models.BooleanField(default=False)),
                ('can_view_analytics', models.BooleanField(default=True)),
                ('can_export_data', models.BooleanField(default=True)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_manage_organization', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('organization_type', models.CharField(choices=[('government', 'Government Agency'), ('ngo', 'Non-Governmental Organization'), ('ingo', 'International NGO'), ('un', 'UN Agency'), ('bilateral', 'Bilateral Donor'), ('multilateral', 'Multilateral Organization'), ('private', 'Private Sector'), ('academic', 'Academic Institution'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('mr', 'Mr.'), ('ms', 'Ms.'), ('mrs', 'Mrs.'), ('dr', 'Dr.'), ('prof', 'Prof.'), ('hon', 'Hon.'), ('', 'No Title')], max_length=10)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('position', models.CharField(blank=True, help_text='e.g., Programme Officer, Technical Advisor', max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True, help_text='Brief professional background')),
                ('profile_picture', models.URLField(blank=True, help_text='URL to profile picture')),
                ('years_experience', models.PositiveIntegerField(blank=True, help_text='Years of experience in development/aid work', null=True)),
                ('specializations', models.TextField(blank=True, help_text='Areas of expertise (comma-separated)')),
                ('languages', models.TextField(blank=True, help_text='Languages spoken (comma-separated)')),
                ('email_notifications', models.BooleanField(default=True)),
                ('dashboard_layout', models.CharField(choices=[('compact', 'Compact'), ('detailed', 'Detailed'), ('cards', 'Card View')], default='detailed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary role/organization for this user')),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this role assignment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='projects.organization')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='projects.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', '-start_date'],
                'unique_together': {('user', 'organization', 'role')},
            },
        ),
    ]
