# Generated by Django 5.2.1 on 2025-05-29 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_role_organization_userprofile_userrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='full_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, help_text='First name', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, help_text='Last name', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Middle name (optional)', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organizational_affiliation',
            field=models.ForeignKey(blank=True, help_text='Primary organizational affiliation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.organization'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='permission_level',
            field=models.CharField(choices=[('organization', 'Organization Level - Can only edit activities for my organization'), ('partner_government', 'Partner Government - Can edit all activities (Super User)')], default='organization', help_text='Determines editing rights within the system', max_length=20),
        ),
    ]
