# Generated by Django 5.2.1 on 2025-05-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_userprofile_full_name_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='secondary_email',
            field=models.EmailField(blank=True, help_text='Optional secondary email address', max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Professional background and expertise'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dashboard_layout',
            field=models.CharField(default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='languages',
            field=models.TextField(blank=True, help_text='Languages spoken'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='specializations',
            field=models.TextField(blank=True, help_text='Areas of expertise'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='years_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
