-- Populate SDG Goals
INSERT INTO sdg_goals (id, goal_name, goal_description, color_hex) VALUES
(1, 'No Poverty', 'End poverty in all its forms everywhere', '#E5243B'),
(2, 'Zero Hunger', 'End hunger, achieve food security and improved nutrition and promote sustainable agriculture', '#DDA63A'),
(3, 'Good Health and Well-being', 'Ensure healthy lives and promote well-being for all at all ages', '#4C9F38'),
(4, 'Quality Education', 'Ensure inclusive and equitable quality education and promote lifelong learning opportunities for all', '#C5192D'),
(5, 'Gender Equality', 'Achieve gender equality and empower all women and girls', '#FF3A21'),
(6, 'Clean Water and Sanitation', 'Ensure availability and sustainable management of water and sanitation for all', '#26BDE2'),
(7, 'Affordable and Clean Energy', 'Ensure access to affordable, reliable, sustainable and modern energy for all', '#FCC30B'),
(8, 'Decent Work and Economic Growth', 'Promote sustained, inclusive and sustainable economic growth, full and productive employment and decent work for all', '#A21942'),
(9, 'Industry, Innovation and Infrastructure', 'Build resilient infrastructure, promote inclusive and sustainable industrialization and foster innovation', '#FD6925'),
(10, 'Reduced Inequalities', 'Reduce inequality within and among countries', '#DD1367'),
(11, 'Sustainable Cities and Communities', 'Make cities and human settlements inclusive, safe, resilient and sustainable', '#FD9D24'),
(12, 'Responsible Consumption and Production', 'Ensure sustainable consumption and production patterns', '#BF8B2E'),
(13, 'Climate Action', 'Take urgent action to combat climate change and its impacts', '#3F7E44'),
(14, 'Life Below Water', 'Conserve and sustainably use the oceans, seas and marine resources for sustainable development', '#0A97D9'),
(15, 'Life on Land', 'Protect, restore and promote sustainable use of terrestrial ecosystems, sustainably manage forests, combat desertification, and halt and reverse land degradation and halt biodiversity loss', '#56C02B'),
(16, 'Peace, Justice and Strong Institutions', 'Promote peaceful and inclusive societies for sustainable development, provide access to justice for all and build effective, accountable and inclusive institutions at all levels', '#00689D'),
(17, 'Partnerships for the Goals', 'Strengthen the means of implementation and revitalize the Global Partnership for Sustainable Development', '#19486A')
ON CONFLICT (id) DO NOTHING;

-- Populate all SDG Targets
INSERT INTO sdg_targets (id, goal_number, target_text, target_description) VALUES
-- Goal 1: No Poverty
('1.1', 1, 'Eradicate extreme poverty', 'By 2030, eradicate extreme poverty for all people everywhere, currently measured as people living on less than $1.25 a day'),
('1.2', 1, 'Reduce poverty by half', 'By 2030, reduce at least by half the proportion of men, women and children of all ages living in poverty in all its dimensions according to national definitions'),
('1.3', 1, 'Social protection systems', 'Implement nationally appropriate social protection systems and measures for all, including floors, and by 2030 achieve substantial coverage of the poor and the vulnerable'),
('1.4', 1, 'Equal rights to resources', 'By 2030, ensure that all men and women, in particular the poor and the vulnerable, have equal rights to economic resources, as well as access to basic services, ownership and control over land and other forms of property, inheritance, natural resources, appropriate new technology and financial services, including microfinance'),
('1.5', 1, 'Build resilience', 'By 2030, build the resilience of the poor and those in vulnerable situations and reduce their exposure and vulnerability to climate-related extreme events and other economic, social and environmental shocks and disasters'),
('1.a', 1, 'Mobilize resources', 'Ensure significant mobilization of resources from a variety of sources, including through enhanced development cooperation, in order to provide adequate and predictable means for developing countries, in particular least developed countries, to implement programmes and policies to end poverty in all its dimensions'),
('1.b', 1, 'Pro-poor policy frameworks', 'Create sound policy frameworks at the national, regional and international levels, based on pro-poor and gender-sensitive development strategies, to support accelerated investment in poverty eradication actions'),

-- Goal 2: Zero Hunger
('2.1', 2, 'End hunger', 'By 2030, end hunger and ensure access by all people, in particular the poor and people in vulnerable situations, including infants, to safe, nutritious and sufficient food all year round'),
('2.2', 2, 'End malnutrition', 'By 2030, end all forms of malnutrition, including achieving, by 2025, the internationally agreed targets on stunting and wasting in children under 5 years of age, and address the nutritional needs of adolescent girls, pregnant and lactating women and older persons'),
('2.3', 2, 'Double agricultural productivity', 'By 2030, double the agricultural productivity and incomes of small-scale food producers, in particular women, indigenous peoples, family farmers, pastoralists and fishers, including through secure and equal access to land, other productive resources and inputs, knowledge, financial services, markets and opportunities for value addition and non-farm employment'),
('2.4', 2, 'Sustainable food production', 'By 2030, ensure sustainable food production systems and implement resilient agricultural practices that increase productivity and production, that help maintain ecosystems, that strengthen capacity for adaptation to climate change, extreme weather, drought, flooding and other disasters and that progressively improve land and soil quality'),
('2.5', 2, 'Genetic diversity', 'By 2020, maintain the genetic diversity of seeds, cultivated plants and farmed and domesticated animals and their related wild species, including through soundly managed and diversified seed and plant banks at the national, regional and international levels'),
('2.a', 2, 'Increase investment', 'Increase investment, including through enhanced international cooperation, in rural infrastructure, agricultural research and extension services, technology development and plant and livestock gene banks'),
('2.b', 2, 'Trade restrictions', 'Correct and prevent trade restrictions and distortions in world agricultural markets'),
('2.c', 2, 'Food commodity markets', 'Adopt measures to ensure the proper functioning of food commodity markets and their derivatives and facilitate timely access to market information'),

-- Goal 3: Good Health and Well-being
('3.1', 3, 'Reduce maternal mortality', 'By 2030, reduce the global maternal mortality ratio to less than 70 per 100,000 live births'),
('3.2', 3, 'End preventable deaths', 'By 2030, end preventable deaths of newborns and children under 5 years of age, with all countries aiming to reduce neonatal mortality to at least as low as 12 per 1,000 live births and under-5 mortality to at least as low as 25 per 1,000 live births'),
('3.3', 3, 'End epidemics', 'By 2030, end the epidemics of AIDS, tuberculosis, malaria and neglected tropical diseases and combat hepatitis, water-borne diseases and other communicable diseases'),
('3.4', 3, 'Reduce premature mortality', 'By 2030, reduce by one third premature mortality from non-communicable diseases through prevention and treatment and promote mental health and well-being'),
('3.5', 3, 'Substance abuse', 'Strengthen the prevention and treatment of substance abuse, including narcotic drug abuse and harmful use of alcohol'),
('3.6', 3, 'Road traffic accidents', 'By 2020, halve the number of global deaths and injuries from road traffic accidents'),
('3.7', 3, 'Sexual and reproductive health', 'By 2030, ensure universal access to sexual and reproductive health-care services'),
('3.8', 3, 'Universal health coverage', 'Achieve universal health coverage, including financial risk protection, access to quality essential health-care services and access to safe, effective, quality and affordable essential medicines and vaccines for all'),
('3.9', 3, 'Reduce pollution deaths', 'By 2030, substantially reduce the number of deaths and illnesses from hazardous chemicals and air, water and soil pollution and contamination'),
('3.a', 3, 'Tobacco control', 'Strengthen the implementation of the World Health Organization Framework Convention on Tobacco Control in all countries'),
('3.b', 3, 'Vaccines and medicines', 'Support the research and development of vaccines and medicines for the communicable and non-communicable diseases'),
('3.c', 3, 'Health financing', 'Substantially increase health financing and the recruitment, development, training and retention of the health workforce'),
('3.d', 3, 'Health risks', 'Strengthen the capacity of all countries, in particular developing countries, for early warning, risk reduction and management of national and global health risks'),

-- Goal 4: Quality Education
('4.1', 4, 'Free primary and secondary education', 'By 2030, ensure that all girls and boys complete free, equitable and quality primary and secondary education leading to relevant and effective learning outcomes'),
('4.2', 4, 'Early childhood development', 'By 2030, ensure that all girls and boys have access to quality early childhood development, care and pre-primary education so that they are ready for primary education'),
('4.3', 4, 'Equal access to education', 'By 2030, ensure equal access for all women and men to affordable and quality technical, vocational and tertiary education, including university'),
('4.4', 4, 'Relevant skills', 'By 2030, substantially increase the number of youth and adults who have relevant skills, including technical and vocational skills, for employment, decent jobs and entrepreneurship'),
('4.5', 4, 'Eliminate gender disparities', 'By 2030, eliminate gender disparities in education and ensure equal access to all levels of education and vocational training for the vulnerable, including persons with disabilities, indigenous peoples and children in vulnerable situations'),
('4.6', 4, 'Youth and adult literacy', 'By 2030, ensure that all youth and a substantial proportion of adults, both men and women, achieve literacy and numeracy'),
('4.7', 4, 'Sustainable development education', 'By 2030, ensure that all learners acquire the knowledge and skills needed to promote sustainable development'),
('4.a', 4, 'Education facilities', 'Build and upgrade education facilities that are child, disability and gender sensitive and provide safe, non-violent, inclusive and effective learning environments for all'),
('4.b', 4, 'Scholarships', 'By 2020, substantially expand globally the number of scholarships available to developing countries'),
('4.c', 4, 'Teacher training', 'By 2030, substantially increase the supply of qualified teachers'),

-- Goal 5: Gender Equality
('5.1', 5, 'End discrimination', 'End all forms of discrimination against all women and girls everywhere'),
('5.2', 5, 'Eliminate violence', 'Eliminate all forms of violence against all women and girls in the public and private spheres, including trafficking and sexual and other types of exploitation'),
('5.3', 5, 'Eliminate harmful practices', 'Eliminate all harmful practices, such as child, early and forced marriage and female genital mutilation'),
('5.4', 5, 'Value unpaid care', 'Recognize and value unpaid care and domestic work through the provision of public services, infrastructure and social protection policies and the promotion of shared responsibility within the household and the family as nationally appropriate'),
('5.5', 5, 'Women''s participation', 'Ensure women''s full and effective participation and equal opportunities for leadership at all levels of decision-making in political, economic and public life'),
('5.6', 5, 'Reproductive rights', 'Ensure universal access to sexual and reproductive health and reproductive rights'),
('5.a', 5, 'Economic resources', 'Undertake reforms to give women equal rights to economic resources, as well as access to ownership and control over land and other forms of property, financial services, inheritance and natural resources'),
('5.b', 5, 'Technology', 'Enhance the use of enabling technology, in particular information and communications technology, to promote the empowerment of women'),
('5.c', 5, 'Gender equality policies', 'Adopt and strengthen sound policies and enforceable legislation for the promotion of gender equality and the empowerment of all women and girls at all levels'),

-- Goal 6: Clean Water and Sanitation
('6.1', 6, 'Safe drinking water', 'By 2030, achieve universal and equitable access to safe and affordable drinking water for all'),
('6.2', 6, 'Sanitation and hygiene', 'By 2030, achieve access to adequate and equitable sanitation and hygiene for all and end open defecation, paying special attention to the needs of women and girls and those in vulnerable situations'),
('6.3', 6, 'Water quality', 'By 2030, improve water quality by reducing pollution, eliminating dumping and minimizing release of hazardous chemicals and materials'),
('6.4', 6, 'Water efficiency', 'By 2030, substantially increase water-use efficiency across all sectors and ensure sustainable withdrawals and supply of freshwater to address water scarcity'),
('6.5', 6, 'Water resources management', 'By 2030, implement integrated water resources management at all levels'),
('6.6', 6, 'Water ecosystems', 'By 2020, protect and restore water-related ecosystems, including mountains, forests, wetlands, rivers, aquifers and lakes'),
('6.a', 6, 'International cooperation', 'By 2030, expand international cooperation and capacity-building support to developing countries in water- and sanitation-related activities and programmes'),
('6.b', 6, 'Local participation', 'Support and strengthen the participation of local communities in improving water and sanitation management'),

-- Goal 7: Affordable and Clean Energy
('7.1', 7, 'Universal access to energy', 'By 2030, ensure universal access to affordable, reliable and modern energy services'),
('7.2', 7, 'Renewable energy', 'By 2030, increase substantially the share of renewable energy in the global energy mix'),
('7.3', 7, 'Energy efficiency', 'By 2030, double the global rate of improvement in energy efficiency'),
('7.a', 7, 'International cooperation', 'By 2030, enhance international cooperation to facilitate access to clean energy research and technology'),
('7.b', 7, 'Energy infrastructure', 'By 2030, expand infrastructure and upgrade technology for supplying modern and sustainable energy services for all in developing countries'),

-- Goal 8: Decent Work and Economic Growth
('8.1', 8, 'Economic growth', 'Sustain per capita economic growth in accordance with national circumstances and, in particular, at least 7 per cent gross domestic product growth per annum in the least developed countries'),
('8.2', 8, 'Economic productivity', 'Achieve higher levels of economic productivity through diversification, technological upgrading and innovation'),
('8.3', 8, 'Development-oriented policies', 'Promote development-oriented policies that support productive activities, decent job creation, entrepreneurship, creativity and innovation'),
('8.4', 8, 'Resource efficiency', 'Improve progressively, through 2030, global resource efficiency in consumption and production and endeavour to decouple economic growth from environmental degradation'),
('8.5', 8, 'Full employment', 'By 2030, achieve full and productive employment and decent work for all women and men, including for young people and persons with disabilities, and equal pay for work of equal value'),
('8.6', 8, 'Youth employment', 'By 2020, substantially reduce the proportion of youth not in employment, education or training'),
('8.7', 8, 'End forced labour', 'Take immediate and effective measures to eradicate forced labour, end modern slavery and human trafficking'),
('8.8', 8, 'Labour rights', 'Protect labour rights and promote safe and secure working environments for all workers'),
('8.9', 8, 'Sustainable tourism', 'By 2030, devise and implement policies to promote sustainable tourism that creates jobs and promotes local culture and products'),
('8.10', 8, 'Financial services', 'Strengthen the capacity of domestic financial institutions to encourage and expand access to banking, insurance and financial services for all'),
('8.a', 8, 'Aid for Trade', 'Increase Aid for Trade support for developing countries'),
('8.b', 8, 'Youth employment strategy', 'By 2020, develop and operationalize a global strategy for youth employment'),

-- Goal 9: Industry, Innovation and Infrastructure
('9.1', 9, 'Develop infrastructure', 'Develop quality, reliable, sustainable and resilient infrastructure, including regional and transborder infrastructure, to support economic development and human well-being'),
('9.2', 9, 'Inclusive industrialization', 'Promote inclusive and sustainable industrialization and, by 2030, significantly raise industry''s share of employment and gross domestic product'),
('9.3', 9, 'Small-scale industries', 'Increase the access of small-scale industrial and other enterprises, in particular in developing countries, to financial services, including affordable credit, and their integration into value chains and markets'),
('9.4', 9, 'Upgrade infrastructure', 'By 2030, upgrade infrastructure and retrofit industries to make them sustainable, with increased resource-use efficiency and greater adoption of clean and environmentally sound technologies'),
('9.5', 9, 'Enhance research', 'Enhance scientific research, upgrade the technological capabilities of industrial sectors in all countries'),
('9.a', 9, 'Facilitate infrastructure development', 'Facilitate sustainable and resilient infrastructure development in developing countries through enhanced financial, technological and technical support'),
('9.b', 9, 'Domestic technology development', 'Support domestic technology development, research and innovation in developing countries'),
('9.c', 9, 'ICT access', 'Significantly increase access to information and communications technology and strive to provide universal and affordable access to the Internet'),

-- Goal 10: Reduced Inequalities
('10.1', 10, 'Income growth', 'By 2030, progressively achieve and sustain income growth of the bottom 40 per cent of the population at a rate higher than the national average'),
('10.2', 10, 'Social inclusion', 'By 2030, empower and promote the social, economic and political inclusion of all, irrespective of age, sex, disability, race, ethnicity, origin, religion or economic or other status'),
('10.3', 10, 'Equal opportunities', 'Ensure equal opportunity and reduce inequalities of outcome, including by eliminating discriminatory laws, policies and practices'),
('10.4', 10, 'Fiscal policies', 'Adopt policies, especially fiscal, wage and social protection policies, and progressively achieve greater equality'),
('10.5', 10, 'Financial markets regulation', 'Improve the regulation and monitoring of global financial markets and institutions'),
('10.6', 10, 'Representation in global institutions', 'Ensure enhanced representation and voice for developing countries in decision-making in global international economic and financial institutions'),
('10.7', 10, 'Safe migration', 'Facilitate orderly, safe, regular and responsible migration and mobility of people'),
('10.a', 10, 'Special and differential treatment', 'Implement the principle of special and differential treatment for developing countries'),
('10.b', 10, 'Development assistance', 'Encourage official development assistance and financial flows'),
('10.c', 10, 'Remittance costs', 'By 2030, reduce to less than 3 per cent the transaction costs of migrant remittances'),

-- Goal 11: Sustainable Cities and Communities
('11.1', 11, 'Safe housing', 'By 2030, ensure access for all to adequate, safe and affordable housing and basic services and upgrade slums'),
('11.2', 11, 'Transport systems', 'By 2030, provide access to safe, affordable, accessible and sustainable transport systems for all'),
('11.3', 11, 'Inclusive urbanization', 'By 2030, enhance inclusive and sustainable urbanization and capacity for participatory, integrated and sustainable human settlement planning and management in all countries'),
('11.4', 11, 'Cultural heritage', 'Strengthen efforts to protect and safeguard the world''s cultural and natural heritage'),
('11.5', 11, 'Reduce disasters impact', 'By 2030, significantly reduce the number of deaths and the number of people affected and substantially decrease the direct economic losses relative to global gross domestic product caused by disasters'),
('11.6', 11, 'Environmental impact', 'By 2030, reduce the adverse per capita environmental impact of cities'),
('11.7', 11, 'Public spaces', 'By 2030, provide universal access to safe, inclusive and accessible, green and public spaces'),
('11.a', 11, 'National and regional planning', 'Support positive economic, social and environmental links between urban, peri-urban and rural areas'),
('11.b', 11, 'Disaster risk reduction', 'By 2020, substantially increase the number of cities and human settlements adopting and implementing integrated policies and plans'),
('11.c', 11, 'Sustainable buildings', 'Support least developed countries, including through financial and technical assistance, in building sustainable and resilient buildings'),

-- Goal 12: Responsible Consumption and Production
('12.1', 12, 'Sustainable consumption', 'Implement the 10-Year Framework of Programmes on Sustainable Consumption and Production Patterns'),
('12.2', 12, 'Natural resources', 'By 2030, achieve the sustainable management and efficient use of natural resources'),
('12.3', 12, 'Food waste', 'By 2030, halve per capita global food waste at the retail and consumer levels and reduce food losses along production and supply chains'),
('12.4', 12, 'Chemical waste', 'By 2020, achieve the environmentally sound management of chemicals and all wastes throughout their life cycle'),
('12.5', 12, 'Reduce waste', 'By 2030, substantially reduce waste generation through prevention, reduction, recycling and reuse'),
('12.6', 12, 'Corporate sustainability', 'Encourage companies, especially large and transnational companies, to adopt sustainable practices'),
('12.7', 12, 'Sustainable procurement', 'Promote public procurement practices that are sustainable'),
('12.8', 12, 'Sustainable development awareness', 'By 2030, ensure that people everywhere have the relevant information and awareness for sustainable development'),
('12.a', 12, 'Scientific and technological capacity', 'Support developing countries to strengthen their scientific and technological capacity'),
('12.b', 12, 'Sustainable tourism', 'Develop and implement tools to monitor sustainable development impacts for sustainable tourism'),
('12.c', 12, 'Fossil-fuel subsidies', 'Rationalize inefficient fossil-fuel subsidies that encourage wasteful consumption'),

-- Goal 13: Climate Action
('13.1', 13, 'Strengthen resilience', 'Strengthen resilience and adaptive capacity to climate-related hazards and natural disasters in all countries'),
('13.2', 13, 'Integrate climate measures', 'Integrate climate change measures into national policies, strategies and planning'),
('13.3', 13, 'Climate education', 'Improve education, awareness-raising and human and institutional capacity on climate change mitigation, adaptation, impact reduction and early warning'),
('13.a', 13, 'Climate finance', 'Implement the commitment undertaken by developed-country parties to the United Nations Framework Convention on Climate Change'),
('13.b', 13, 'Climate planning', 'Promote mechanisms for raising capacity for effective climate change-related planning and management'),

-- Goal 14: Life Below Water
('14.1', 14, 'Marine pollution', 'By 2025, prevent and significantly reduce marine pollution of all kinds, in particular from land-based activities'),
('14.2', 14, 'Marine ecosystems', 'By 2020, sustainably manage and protect marine and coastal ecosystems to avoid significant adverse impacts'),
('14.3', 14, 'Ocean acidification', 'Minimize and address the impacts of ocean acidification, including through enhanced scientific cooperation at all levels'),
('14.4', 14, 'Sustainable fishing', 'By 2020, effectively regulate harvesting and end overfishing, illegal, unreported and unregulated fishing and destructive fishing practices'),
('14.5', 14, 'Marine conservation', 'By 2020, conserve at least 10 per cent of coastal and marine areas'),
('14.6', 14, 'Fisheries subsidies', 'By 2020, prohibit certain forms of fisheries subsidies which contribute to overcapacity and overfishing'),
('14.7', 14, 'Marine resources benefits', 'By 2030, increase the economic benefits to small island developing States and least developed countries from the sustainable use of marine resources'),
('14.a', 14, 'Marine research', 'Increase scientific knowledge, develop research capacity and transfer marine technology'),
('14.b', 14, 'Small-scale fishers', 'Provide access for small-scale artisanal fishers to marine resources and markets'),
('14.c', 14, 'International law', 'Enhance the conservation and sustainable use of oceans and their resources by implementing international law'),

-- Goal 15: Life on Land
('15.1', 15, 'Terrestrial ecosystems', 'By 2020, ensure the conservation, restoration and sustainable use of terrestrial and inland freshwater ecosystems and their services'),
('15.2', 15, 'Sustainable forests', 'By 2020, promote the implementation of sustainable management of all types of forests, halt deforestation, restore degraded forests'),
('15.3', 15, 'Combat desertification', 'By 2030, combat desertification, restore degraded land and soil, including land affected by desertification, drought and floods'),
('15.4', 15, 'Mountain ecosystems', 'By 2030, ensure the conservation of mountain ecosystems, including their biodiversity'),
('15.5', 15, 'Biodiversity', 'Take urgent and significant action to reduce the degradation of natural habitats, halt the loss of biodiversity'),
('15.6', 15, 'Genetic resources', 'Promote fair and equitable sharing of the benefits arising from the utilization of genetic resources'),
('15.7', 15, 'End poaching', 'Take urgent action to end poaching and trafficking of protected species of flora and fauna'),
('15.8', 15, 'Invasive species', 'By 2020, introduce measures to prevent the introduction and significantly reduce the impact of invasive alien species'),
('15.9', 15, 'Ecosystem values', 'By 2020, integrate ecosystem and biodiversity values into national and local planning'),
('15.a', 15, 'Financial resources', 'Mobilize and significantly increase financial resources from all sources to conserve and sustainably use biodiversity and ecosystems'),
('15.b', 15, 'Forest resources', 'Mobilize significant resources from all sources and at all levels to finance sustainable forest management'),
('15.c', 15, 'Combat poaching', 'Enhance global support for efforts to combat poaching and trafficking of protected species'),

-- Goal 16: Peace, Justice and Strong Institutions
('16.1', 16, 'Reduce violence', 'Significantly reduce all forms of violence and related death rates everywhere'),
('16.2', 16, 'End child abuse', 'End abuse, exploitation, trafficking and all forms of violence against and torture of children'),
('16.3', 16, 'Rule of law', 'Promote the rule of law at the national and international levels and ensure equal access to justice for all'),
('16.4', 16, 'Combat crime', 'By 2030, significantly reduce illicit financial and arms flows, strengthen the recovery and return of stolen assets and combat all forms of organized crime'),
('16.5', 16, 'Reduce corruption', 'Substantially reduce corruption and bribery in all their forms'),
('16.6', 16, 'Effective institutions', 'Develop effective, accountable and transparent institutions at all levels'),
('16.7', 16, 'Inclusive decision-making', 'Ensure responsive, inclusive, participatory and representative decision-making at all levels'),
('16.8', 16, 'Global governance', 'Broaden and strengthen the participation of developing countries in the institutions of global governance'),
('16.9', 16, 'Legal identity', 'By 2030, provide legal identity for all, including birth registration'),
('16.10', 16, 'Public access to information', 'Ensure public access to information and protect fundamental freedoms'),
('16.a', 16, 'Strengthen institutions', 'Strengthen relevant national institutions, including through international cooperation'),
('16.b', 16, 'Non-discriminatory laws', 'Promote and enforce non-discriminatory laws and policies for sustainable development'),

-- Goal 17: Partnerships for the Goals
('17.1', 17, 'Domestic resources', 'Strengthen domestic resource mobilization, including through international support to developing countries'),
('17.2', 17, 'ODA commitments', 'Developed countries to implement fully their official development assistance commitments'),
('17.3', 17, 'Additional resources', 'Mobilize additional financial resources for developing countries from multiple sources'),
('17.4', 17, 'Debt sustainability', 'Assist developing countries in attaining long-term debt sustainability through coordinated policies'),
('17.5', 17, 'Investment promotion', 'Adopt and implement investment promotion regimes for least developed countries'),
('17.6', 17, 'Technology cooperation', 'Enhance North-South, South-South and triangular regional and international cooperation on and access to science, technology and innovation'),
('17.7', 17, 'Technology transfer', 'Promote the development, transfer, dissemination and diffusion of environmentally sound technologies to developing countries'),
('17.8', 17, 'Technology bank', 'Fully operationalize the technology bank and science, technology and innovation capacity-building mechanism for least developed countries'),
('17.9', 17, 'Capacity building', 'Enhance international support for implementing effective and targeted capacity-building in developing countries'),
('17.10', 17, 'Multilateral trading', 'Promote a universal, rules-based, open, non-discriminatory and equitable multilateral trading system under the World Trade Organization'),
('17.11', 17, 'Exports of developing countries', 'Significantly increase the exports of developing countries'),
('17.12', 17, 'Duty-free market access', 'Realize timely implementation of duty-free and quota-free market access on a lasting basis for all least developed countries'),
('17.13', 17, 'Global macroeconomic stability', 'Enhance global macroeconomic stability, including through policy coordination and policy coherence'),
('17.14', 17, 'Policy coherence', 'Enhance policy coherence for sustainable development'),
('17.15', 17, 'Respect policy space', 'Respect each country''s policy space and leadership to establish and implement policies for poverty eradication and sustainable development'),
('17.16', 17, 'Global partnership', 'Enhance the Global Partnership for Sustainable Development, complemented by multi-stakeholder partnerships'),
('17.17', 17, 'Public-private partnerships', 'Encourage and promote effective public, public-private and civil society partnerships'),
('17.18', 17, 'Capacity for data', 'By 2020, enhance capacity-building support to developing countries to increase significantly the availability of high-quality, timely and reliable data'),
('17.19', 17, 'Measurements of progress', 'By 2030, build on existing initiatives to develop measurements of progress on sustainable development')
ON CONFLICT (id) DO NOTHING; 